-- SELECT *
-- FROM STUDENTS

-- SELECT NAME, AGE
-- FROM STUDENTS

-- SELECT NAME AS COL1, AGE AS COL2
-- FROM STUDENTS

-- SELECT *
-- FROM STUDENTS
-- WHERE AGE >= 30

-- SELECT *
-- FROM STUDENTS
-- WHERE NAME = '김정호'

-- SELECT DISTINCT ADDRESS
-- FROM STUDENTS

-- SELECT DISTINCT ADDRESS, NAME, AGE
-- FROM STUDENTS