-- SELECT * FROM STUDENTS;

-- DELETE FROM STUDENTS
-- WHERE AGE = 19;

-- SELECT * FROM STUDENTS;

-- DELETE
-- FROM students
-- WHERE age BETWEEN 30 AND 33;

-- SELECT * FROM students;

-- DELETE
-- FROM students;

-- SELECT * FROM students;